ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      use-forwarded-headers: "true"
      keep-alive: 10
      hide-headers: "Server,X-Powered-By"
      enable-ocsp: "true"
      hsts-preload: "true"
      enable-modsecurity: "true"
      enable-owasp-modsecurity-crs: "true"
      enable-brotli: "true"
      load-balance: "ewma"
    ingressClassResource:
      default: true

    kind: DaemonSet
    minAvailable: 1
    maxUnavailable: 1

    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 400Mi

    minReadySeconds: 30

  revisionHistoryLimit: 0

  defaultBackend:
    enabled: true
    image:
      repository: ghcr.io/tarampampam/error-pages
      tag: 3.3.0
    extraEnvs:
      - name: TEMPLATE_NAME
        value: ghost
      - name: SHOW_DETAILS
        value: 'true'
    resources:
      limits:
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 10Mis