argo-cd:
  global:
    revisionHistoryLimit: 0
    logging:
      format: json
      level: info
  
  configs:
    cm:
      create: false
      exec.enabled: true
    secret:
      createSecret: true
    rbac:
      create: false

  controller:
    replicas: 1
    resources:
      limits:
        memory: 1024Mi
      requests:
        cpu: 130m
        memory: 512Mi

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

  dex:
    enabled: false

  redis-ha:
    enabled: true
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    exporter:
      enabled: false

  server:
    replicas: 2
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 70m
        memory: 128Mi
  
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hostname: argo.sealeo.io
      tls: true
      extraHosts:
        - name: argo.internal.sealeo.io
          path: /

    configEnabled: false

    rbacConfigCreate: false

  repoServer:
    replicas: 2
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 256Mi

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false

  applicationSet:
    replicas: 0
    serviceAccount:
      create: false
      allowAnyNamespace: false
      
  notifications:
    enabled: false
