---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: prometheus
spec:
  encryptedData:
    admin-password: AgC+FQzMhvj/FG6J/ossXMo1NIhuywi8hrZ3V2T5kvrAYt3j7lUPCrcTugtTXZneAsk+jK4jQy2FIP8KGkALvS1th/ySMdEy/nv8alLDpxyevEH3nRjCQw3LB8M6u/w41EIip3OgKaxvE9mDBl82cXqV93GplxF1j2TTjpysc9pv/5Stwh1K4EtB3fDsvd4Poufu7cKOOXYS6yDpDjiZ1C/ybncPtj0GfOU7rKgvVXXsA51px9JDhIpH0vzrBYo7X8Vfvxx5iP7fbPLRUGJNv8VHUSYF5XtEPLprGwaYOEmKlfJtYqM0SzLw2TDo2lQ1DmrEkjIsiPAfhWOPjMYcZCVLyMj2gqzPCTFHdUPhK9kM19M0gbfeDD3gHguUOZ3bBtk4bqlyamrS9ZDuBq9HA7dEefePQXlFoAVCzZAurfW8O8UYyCasX/N0N54I+UQBLJpHcbAa1dQxp6XjBvqxNWe7jJUrvDHVKegPV1BmsAN4Ouxp7FyySIgNluN+QTg/Jl+P5MIji7MSsJd3ZNF7zzyKtXiYEPVwIMIYGGd+YhxzEI4MpB0EMetdS9UKYDQo+Vq4v0gaDa/LJeYzYag4Q7Oj2DKFTj26N8kQmWmzNNuMLalNVkDd21ji7Nz1X5jg5h2jzcltEuF4IgB/hDuZk2tyEwLiqYTGU21VKp0ssN3Wrx62dTrabjw4sEjdknjb+Vz60zdyPUpy5pTkCr3KdDZE2i3i0I9MxPCz5HB/JfEPsp371MGpZk59ynQY17N9
    admin-user: AgA7OCNW9XmPqBn3lukvP/sr5VocBOOadjJ3Z9NMRI2CQ8ytWDJb2DOl942tLq+T11QgSFONnTBeNUONOgOpXAb78taXBErEfW8c0e1UNVKtOSlZ1ijAFdy+F/T8NyZP5ho8vlrV48LAIhTSjcJvEIGkawC3Rn3etgJMKYv2bmHzJDndDwIP7J6QdxvO65CBD6taFdNOgJnAUotxnQvlS6wmLVjCIdbaCGDxY8EWT6mvc6XFdtK3DXyMTK++crqAzZC4Rhju6hkajVGE/kij+lqAiY66Ew/0+eNSHwb7deQvmXk1rKCb4PfAt/qyjzP2s6HDQ5iqS9RTq0YTlsYwjfUqxa7CWeJUAxtJAKXwl+qeZuwslQqjj7gNAYMDoMkEmhkMZQTQCDpIZRn87G6LmalHJa/DOKxGdilR15z8BwCcpoe5Wlyb5OEIaKiEXz3Aty3BfnRYUsRRpjoMMNHj53j9HtAr00W/RUppYSxVYdEXMbe5u5XwDkvyHKj3EdBkd70h21KSGbAGoooQnkFvE6U1g27O9gxiWZ30vMvyDY+iQkuwMYvpGbwqQc3bIybkCwxwAyfyuNY9eOWuuiKhWU3+IkWEp58G2dlHQhlqIypSbMfi6Um3scc5OFeS5D+5aO7K8T2YPYoS8sWasv/FBbSfG/+eC7OdnaNiyTA1KvBdwut6yfGDI0hJWJIXO5xmgZyYi1LOfw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: prometheus
    type: Opaque
