---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    databasePassword: AgC96OEvM8dKS4BtMygMJWKl+qDSZ4JuR1bCaXnveYpLwimNEBR9z1DtMoJYdYZdZomoWqk6Y+imE/LNE4S0QpYbpEKLYxVH6Wh+lHq9MxM6ueUn8qVmWjvvZO/pXXE164isx7u8mPyPjd7px4tNaaA4VeCiGBtJwRRC2PZQT7FoVAUVHOxPEq2Q/G6ejgXEUjN0OSsXdqQIFALzoU9c7h8EWK4BzArc13+Ye+Zjof6LJa0K3SbLxlDmohkhbtq+KUEt1FHuDlHW1fH0ybJSAQC4TgOmTd9CmfblIHt3XwSrCIe6I7a8xsBAdEN0+NZiVjG1XYcKHBMda44u6Jrm+pCeJms3nNVFEEnupZNQHhq5BXURLV55efwEffqZ3APXXtG0b47r4L4saaNyNXXAZ49lbb2Z4ZJoSZ8pmsS649WTUqZlCsYTAmeXYHDfBNVTaCeGWRdCe4P7Md2fawLah/qjqsp7yaPGwjyK+ppP4se8l6LGl2JT7UXHQEh7NtkSlHuP4mcRqkkbTUKIo5OiIWjw9PxeEW+VISZBhKURlVdz0D3iAkGHKZPIPe7L7U5FIjO2cAT3F8RAOfnL8ZsRM/abgnQAb5vZBU5L6LKXnuj/w7jmfhMvWl4Z5Zz9QH3Cm32TmNqzeU5eW3AP5Rk77ieSeeEOsczSIcat+s7/I20Nb9eYIRtEQvkCsbYEP3REVUddqpSOAMfHKZ34MxwNaLs8Jn/vnhWkUeKxgLzzZcbJz0OH83Eng6tBtW1SqRx9QJ+DEmVQTV0sW70inLxCC3vU
    secretKey: AgA26x4+0TfqSzxr9e9mss3fF4gx4+e4m1beaJPyeEsuk2Lq+oylXFn10W4dUCfhKkvaW8xoF2CyqM9zrlrEEKk8AOQACoXds+WtneTU34f6nKwLXrSOYyHtnKFxSzI49BOBH2XHvb3d1dRSP0SBncv23aA8wqhOPN6+I8JSm9qYnyAkT/gFeI5KWPDNNGxVovJCaCaRA491p9fsJRiUXrriXZLZ5Tzj1HpLwCJkMutz2+vDVnDvNiaPKAh9At2coe6edB2j3+We2Gk5P65EkqbF35sKn4wjS/u7EH17Rd1ZBmyMQFoO8VGAcWGG03lNrGqbY1p3DIqEmfLACIcYpydFvzUP6FHvqFk0yAA0FFsRi0MWbxlaPYEHJvQUsAvcfyrEV9J1LqwoN+awG+pZbIAOgecnGSX22Vc+ZGyYcUmtK70mretNDaGuLdPM/GUztolXsIbyDhwErs+4B5OvrACvzYFcAgOD9E5WzNL8nOpo/aHPupOdKzjN4D6pk7uAqoufmbk/owDiWbpagKSNYo0vZSQUfsKG8y1EeToKy6c9ZJkGqDdX1pgORssbN46PQf7FGlyxG0I+78zJUl6Z0SaqOd2Et7wlMznQZLBL1LMOkmnfn97AnYfJRIaYQVk0eb4Amv7TL3NOj4TojIALA5gAsIKNlSldX0FVBFzPJBZ1U0MzqJ2k8bpVA2sUmUBTKg80Of6kulzB9fk0O4CUeG198zeXIiGExIO9+ei2eK2MeYee/gXGAqHjidbhlkH96uBDAg==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
    type: Opaque
