---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    databasePassword: AgCuazbwefs8zbWeau5rVKz08pnisIKzh7swmsEznrwyty88iEWVg4VOc0pSPqvEgV6czJbCTBZmsQb4FMYkwfEGFOp6G3YUcmOkGM0m0fgWQX5y2ka/8Re3AgESXpnJIGI1Cs8IZfdZf329Vlhsa7NZqiFrtj9rTAGKXQ7h3c/eItBCmwmPDm3Mo3DeEJx+6Roo/dtkoIL3sQphzrtNZwnrRq0QQuxbjhJPz5629gDNSv0gIhxnN8XbhgZZicAK4WtrTxhb5eS1mFIoDtrW7Nv/a1H+v2eUVkqwmF+2hfut2SBYVbwBu/voxoziVw4+7CUYl0lXBmWbE0eoKFCdtPm6XARp0CCkOJ9bSriOGiUWODQ4BLMRGaSCqK8AGawmMDqaiarO2uZMdjb5AhIcJ0395a3xcCP6joDWp/PIR8Orincm44/5THxNvFOZhSqV74FpgURLqwo1F0JPt7JYPN3j4nM02tLK9LNv/8U1bgKktEPqBaQYt3qWy5uYgzJ+ML1me9UCQiPXM11HiNfkrmbLC0wy4QGjpAf8odGdYdRhuzIILO9s+mQlPV40ZLp+9MGJCDJdjgSr9klsnlCCo/uo0pBi+4v8yo9V1sPn3mLTb9+Lsnzo2WNR4gL12wHMqzLLL3ihAe8ZB/9G5EKsCO2BtE5jYIKxw5hzLMrwG5NeQoa1qIkkma6IymrLbbdOBKBpSgbfr8eb5JKARHIuS8ZAdZ557Z/Q3dbwbHQmz4F+VGxuKBN5Sk5PbraEmXkydiY8hltqXGBnnYCUqSnG/+g5
    secretKey: AgB1q0g7ADJpTglBMEgEDjF0ubJe8RvOAo9ZZ6T8ahMtP8jig/yp4HVUQ7V6/ul0m9htSKH0LKgzPakCOawd/aqzuqJHhoqw8R81GgqPr/XzP71IZQcIC+4tUxcao2mH+VA7vzCY7CPQ+1qS7UwYZQLqGkZE0NEJUiJ6xBBmQ1cb/G5PLaHqmYw6LV2pyJIIOq2k7FeY1jKlAledxbaejgpiZAajjCFxtHqUaNmfztbPWtmAAeVyeY/yaq+duNPdBBskan9edy/TA2sbsO0B4h+cX7pJbhjXAMRDbsRQ7db4j0Vnoc3vEtgIW5LmW8AtEMu4au1Omz9DZFC35bK6dkwYY1VKZUlb/0FLKYzXraQULIA0bi1h8/SjwWZk9h9wW8wa/FRtA16Vg45xplvjHs7IsRjzo7wmMseGOBb0UxoRM9yTSKj5jkxYwbmcCPa7rzS2XqDKXSZ7i0Bzu2W/zNhSxur4n0MrS5gOdOcRP6E54zZR3ZKb5VOThzEFwCrs/+pFdVcrvdHpZnHLDrxhe0NP+p0PTCJvTgZ87zX5JxgjUbk+R4Mc2Q3dOEHbB5jy0cT7z3qPCOCqXEypgoMGvDxEGio7JjcHusmUDsgGMT9KwjLDGYD/F0FGelwRY8FlWyNnXj1vs0ExJ9Kxoa35KvcsJjJRmQxJF897XARhRV++zsUN+pm8kkVlpu6/MWy1MfqyOyjAUsmLNzdGCvNBeDoeat3oSnQRQa+pkcKbl3Yb6/3qeUV024sHxmzTUXBYHfXtEw==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
    type: Opaque
