---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secret
  namespace: authentik
spec:
  encryptedData:
    databasePassword: AgB3jQ0vcdfE/4/BZHX+cjULq4N9J6RvSjfUgox5Ef9a5f0syGQyZTw/ZsMzsTcXVyTrkdMj3UCzAgPmvT/+/3nG0UHmpGbJMDCdOGJRVUraa2ZF9VQA+y383liWdyakJbbXyIncYk+bRYSjevblViCEz7Ik03yfgod89GWP/eE/p1IkW0abskeCAUrONW0YEzOBmxlGVpQvUHvhtG46YMe1kJ1Gp9H7evgDPkpkArEFglvuxqC7JZDJOkis3X22EJjQAcLPp74AfGA7mik5b6k7mLpTsz/SLV7+4RPt/qe7ukO4hcTHpnek4MlB6qoEnCOITRqj9NkQ/T+sgDNqfWIY2BVak/tKE2gIQ9ImvSYZsCfmeu6msRlULfWr11f9NU2G28EAHlb8RfVmJZl4Q711scm1iNEZkguVs3eVjk0gbRK1t7Y4vsNEwTvH5qCSw6Vg2Leu7llb5QzkCVo8KuETM3TiQETntRzs2++rAssVgFoklsvJs6HrwNrX/xdAyTaCh6C0ZcrB/MYZaOyYuUqp6SFtH2uyTDgxABmM8uJefFm0x8wwUH0RbXcr8R/s5vpJrQ7unknvQ5vNT7l5mpSkhj6PA9UJq2A+HExVCuqf7KXJkOi9+UEcTuVyc4MMbkjRpKFRj/ISYPxw+yllaARhwDvxR+720jlVGJnCJB+aINMuCCileGaRH2iHhe5g2JtydjYKqOj3Ce+qkbFQhKYb76Wp3iqp/tKNZ+VX9i1H/KaWbZdB4qewazBQuDE4HtVgsLp3Wv56NdTKb2R609rS
    secretKey: AgAk/3l6qXyETmQmKpkwL7CPAhMUQMF3UtOj9EgZpX2xcZV3OA/PcbctUK+zspYotW6mEL5ijMw6KihqY7aPA7wEMyswz317z4nzvELJu20CRRW4zZnCcGw59trJhhvLCr5yXBI+pQocSO02huzc9rDMmk8pyZSzYJ3fPRSoJPqCKaCchMgWofYsdTks+xggMyIw9gbUEU3pKmDNZ4X3MFBNUmZYSSdn9MZNiFF5hBQ6vkzU7UWQr/Qk2VJgWLTuOV9fDB0vWSqbgbMrFwPFlMppOxfcN7RKr0P1cXhjVV3hlqKUPH5k89sQzcZBjgTnzn5fa2eR+UA78DFkldsC14dje4Ucr04m/SmrZ7NhkiSSYVsYqz8EIoz0S5iJxZzzHvao7nuqCKuESsIFkPmtPljJXnq6PYh2kEemg7gf/J6iCH61E9qMiEjbmDvft2YhDr56ssZGDsIJluuMxyr870+fhvLMOJkyDhD4CVOluSq5P4cvtL3lQuclWqBC9/SmshCL11KUKg1ZG0jJXaRBqeE3lN+HCGrB6ezQAD3Rzt8HlaSmlQ9n12rH31Wc/V66xw9t1z9RR7o2tmwrNDQDTDL2zNDKqYyXVWABj28AmPHQPF+YWGlLVPnoL/2tC9Oc1Ttk23JCpDGcGMsVn7/0qkmKB5z6FWqHt6WIrQ//qUOYAKHWVYaO+wScqZ005TtveyNt4V6mCkF5xrGlXMDPft0YloFrkpP9iBNL/DzNbg+v8FNW2zoUYflQ6z+b+oK3/IGXpA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secret
      namespace: authentik
    type: Opaque
