apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: lhhl-base-chart:argoproj.io/Application:argocd/authentik
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"lhhl-base-chart:argoproj.io/Application:argocd/authentik"},"finalizers":["resources-finalizer.argocd.argoproj.io"],"name":"authentik","namespace":"argocd"},"spec":{"destination":{"namespace":"authentik","server":"https://kubernetes.default.svc"},"project":"default","revisionHistoryLimit":1,"source":{"path":"products/authentik","repoURL":"https://github.com/LuukHors/homelab.git","targetRevision":"HEAD"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"retry":{"backoff":{"duration":"5s","factor":5,"maxDuration":"10m"},"limit":5},"syncOptions":["ServerSideApply=true"]}}}
  creationTimestamp: "2026-05-15T22:49:05Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 61
  name: authentik
  namespace: argocd
  resourceVersion: "550713"
  uid: 5b32b5b5-280c-4748-b1d9-689561c2d314
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 1
  source:
    path: products/authentik
    repoURL: https://github.com/LuukHors/homelab.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
      limit: 5
    syncOptions:
    - ServerSideApply=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2026-05-15T22:54:48Z"
    status: Healthy
  history:
  - deployStartedAt: "2026-05-15T22:53:10Z"
    deployedAt: "2026-05-15T22:53:11Z"
    id: 1
    initiatedBy:
      automated: true
    revision: 5eaca3f2a5d0a0fd38f1ef4949c9d50c56883fcb
    source:
      path: products/authentik
      repoURL: https://github.com/LuukHors/homelab.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2026-05-15T22:54:31Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        backoff:
          duration: 5s
          factor: 5
          maxDuration: 10m
        limit: 5
      sync:
        autoHealAttemptsCount: 5
        prune: true
        resources:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          name: authentik-server
        revision: 5eaca3f2a5d0a0fd38f1ef4949c9d50c56883fcb
        source:
          path: products/authentik
          repoURL: https://github.com/LuukHors/homelab.git
          targetRevision: HEAD
        syncOptions:
        - ServerSideApply=true
    phase: Succeeded
    startedAt: "2026-05-15T22:54:31Z"
    syncResult:
      resources:
      - group: gateway.networking.k8s.io
        hookPhase: Running
        kind: HTTPRoute
        message: httproute.gateway.networking.k8s.io/authentik-server serverside-applied
        name: authentik-server
        namespace: authentik
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 5eaca3f2a5d0a0fd38f1ef4949c9d50c56883fcb
      source:
        path: products/authentik
        repoURL: https://github.com/LuukHors/homelab.git
        targetRevision: HEAD
  reconciledAt: "2026-05-15T22:54:31Z"
  resourceHealthSource: appTree
  resources:
  - kind: Namespace
    name: authentik
    status: Synced
    version: v1
  - kind: Secret
    name: authentik
    namespace: authentik
    status: Synced
    version: v1
  - kind: Service
    name: authentik-server
    namespace: authentik
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: authentik
    namespace: authentik
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: authentik-server
    namespace: authentik
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: authentik-worker
    namespace: authentik
    status: Synced
    version: v1
  - group: bitnami.com
    kind: SealedSecret
    name: authentik-secret
    namespace: authentik
    status: Synced
    version: v1alpha1
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: authentik-server
    namespace: authentik
    status: OutOfSync
    version: v1
  - group: postgresql.cnpg.io
    kind: Cluster
    name: authentik-postgres
    namespace: authentik
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: authentik-authentik
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: authentik-authentik
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: authentik
    namespace: authentik
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: authentik
    namespace: authentik
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    images:
    - ghcr.io/cloudnative-pg/cloudnative-pg:1.29.1
    - ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
    - ghcr.io/goauthentik/server:2025.12.4
  sync:
    comparedTo:
      destination:
        namespace: authentik
        server: https://kubernetes.default.svc
      source:
        path: products/authentik
        repoURL: https://github.com/LuukHors/homelab.git
        targetRevision: HEAD
    revision: 5eaca3f2a5d0a0fd38f1ef4949c9d50c56883fcb
    status: OutOfSync
