apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo.internal.sealeo.io
  admin.enabled: "false"
  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "true"

  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"

  oidc.tls.insecure.skip.verify: "false"
  oidc.config: |
    name: Authentik
    issuer: https://auth.internal.sealeo.io/application/o/argocd/
    clientID: LN03nETlGuUWWCMVdmoTTZUeZIHepi6z6DF3n7UC
    clientSecret: $authentik-credentials:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: https://auth.internal.sealeo.io/application/o/argocd/end-session/
