apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo.internal.sealeo.io
  admin.enabled: "true"
  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "false"

  oidc.tls.insecure.skip.verify: "false"
  oidc.config: |
    name: Authentik
    issuer: https://auth.internal.sealeo.io/application/o/argo/
    clientID: gSSa5CRgsI1830mcpfTBietHEz6PrbvOYPWADpih
    clientSecret: $authentik-credentials:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: https://auth.internal.sealeo.io/application/o/argo/end-session/
