apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "true"
  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "true"

  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"

  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"

  url: https://argo.internal.sealeo.io
  additionalUrls: |
    - https://argo.sealeo.io
  oidc.tls.insecure.skip.verify: "false"
  oidc.config: |
    name: Authentik
    issuer: https://auth.internal.sealeo.io/application/o/argocd/
    clientID: FPs1rDh75YjdD1QBfCF3EjpXMVbdBWAw5ImEQl6V
    clientSecret: $authentik-credentials:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: https://auth.internal.sealeo.io/application/o/argocd/end-session/