apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo.sealeo.io
  admin.enabled: "true"
  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "true"

  oidc.tls.insecure.skip.verify: "false"
  oidc.config: |
    name: Authentik
    issuer: http://authentik-server.authentik.svc.cluster.local/application/o/argo/
    clientID: gSSa5CRgsI1830mcpfTBietHEz6PrbvOYPWADpih
    clientSecret: $authentik-credentials:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: http://authentik-server.authentik.svc.cluster.local/application/o/argo/end-session/