apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  timeout.reconciliation: 180s
  cluster.inClusterEnabled: "true"

  resource.customizations.health.argoproj.io_Application: |
    hs = {}
    if obj.status ~= nil and obj.status.health ~= nil then
      hs.status = obj.status.health.status
      hs.message = obj.status.health.message
    else
      hs.status = "Progressing"
      hs.message = "Waiting for child application health status"
    end
    return hs

  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
    - apiGroups:
        - tekton.dev
      kinds:
        - PipelineRun
        - TaskRun
      clusters:
        - "*"
      namespaces:
        - gitea

  url: https://argo.internal.sealeo.io
  oidc.tls.insecure.skip.verify: "false"
  oidc.config: |
    name: Authentik
    issuer: https://auth.internal.sealeo.io/application/o/argo-cd/
    clientID: R2Fm0u5ls7of2eAOPuo53Vw2GI10K0CcNwZDHQbC
    clientSecret: $authentik-credentials:clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: https://auth.internal.sealeo.io/application/o/argo-cd/end-session/
