---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-credentials
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgBwYV4aC5xHWq/s9NVz5eppumPc9fgt2h59Yrl6E5AO1mVhq+y7t1h19azYJFq5SWNc72FDe5gxCIvQOrArlC0ySCFL90NmwJ4q9cdoKrrubBT/POektO89ysXZEz1CAdnW7UdOZxihB50RvLT1SPtYfZkygqTg0FbyDsO4V5N0WVSwbCLZJTSiR2N/j721MMwEZRFDkBph75ysqqMsu8uJ89pqHtiLtt+RhP8VDbOtmeRlS1sRmjJfmYOhDtm+NYfCBLuWZvqdxIyXhaxIVb7ziUQQxMIfc8z8epwh78BRPM3UfC2tCKPOC1nPBN4dwENADxFXeU1xls6O0pCIAZpbnqlHzNLBZmwRjvqhRIviUDc/8n5rTlA4NnRXDqhOl2lsz3/WmIqZuBbTWjNQdErKtWK5noYvhyFgZZZZs/k4n9oN1Fm2fnOe8XIeMYj92podfddVNuG0Cg5gZgAtTMsNOX65soLxHPI6Z1MCQO5uWf1MaJzXc3UcY0129ZnKE7Z4/h34Sg4/jFM/S5l3ERhQvcoxVhUbW+fMvNXXfLCMI+iuJHw0TFzJSRyAT5JkV6230h0SxViCWC92fdozfRLnkOxStidi2BIN7p5+orM3DY1rnVrIrqndRwqDkoexTgJlBxZQ5at8Z70qap1ne0s0aUeDK1IR5JfBO4IbH2Dq0yH/knbgAljwtFFllITYmglN5axMPrputnAABZHFfhedIhIb2eepBjD+Egd2MAbH9oFUlf3IBiyCSvcy722xLeBaQLkyq6nkECUxu/C23eXZrWqmdCLPZi3sMh1tlmk0B3A1ppL9A0CDHFtjso7oksZ8JqJAIjInZwj5NzdHA9I5bQjq/V8WSmBK3mwUUWY+Dg==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: authentik-credentials
      namespace: argocd
    type: Opaque
