{{- if .Values.homelab.deploy }}
{{- range $productName, $productInfo := .Values.homelab.products }}
{{- if $productInfo.deploy }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $productName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LuukHors/homelab.git
    targetRevision: {{ default "HEAD" $productInfo.targetRevision }}
    path: products/{{ $productName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ default $productName $productInfo.namespace }}
{{- with $productInfo.ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml . | nindent 4 }}
{{- end}}
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
---
{{ end -}}
{{ end -}}
{{ end -}}
