{{- if .Values.homelab.deploy }}
{{- range $productName, $productInfo := .Values.homelab.products }}
{{- if $productInfo.deploy }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $productName }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LuukHors/homelab.git
    targetRevision: init-homelab
    path: products/{{ $productName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $productName }}
  revisionHistoryLimit: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
{{ end -}}
{{ end -}}
{{ end -}}