apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener 
metadata:
	name: gitea-pr-eventlistener
spec:
	serviceAccountName: pr-eventlistener-service-account
triggers:
	- name: gitea-pr-listener
		bindings:
			- ref: gitea-pr-triggerbinding
		template:
			ref: gitea-pr-pipeline-template