apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pr-eventlistener-role-binding
subjects:
- kind: ServiceAccount
  name: pr-eventlistener-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles