external-dns:
  sources:
    # - crd
    - service
    - ingress

  provider: cloudflare

  extraArgs:
    exclude-target-net: 192.168.178.245/24

  validation:
    enabled: true

  cloudflare:
    secretName: "cloudflare-api-token"
    proxied: true

  domainFilters: []

  excludeDomains:
    - 'internal.sealeo.io'

  regexDomainFilter: ""
  regexDomainExclusion: ""

  dryRun: false
  policy: sync

  crd:
    create: false

  service:
    revisionHistoryLimit: 0
    enabled: true

  serviceAccount:
    create: true

  rbac:
    create: true

  pdb:
    create: true

  metrics:
    enabled: false
