external-dns:
  sources:
    # - crd
    - service
    - ingress

  publishHostIP: true
  provider: cloudflare

  validation:
    enabled: true

  cloudflare:
    secretName: "cloudflare-api-token"
    proxied: true

  domainFilters: []

  excludeDomains:
    - 'internal.sealeo.io'

  regexDomainFilter: ""
  regexDomainExclusion: ""

  dryRun: false
  policy: sync

  crd:
    create: false

  service:
    enabled: true

  serviceAccount:
    create: true

  rbac:
    create: true

  pdb:
    create: true

  metrics:
    enabled: false
