apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitea-pr-triggerbinding
spec:
  params:
    - name: gitea-url
      value: $(body.repository.url)
    - name: sha
      value: $(body.after)