homelab:
  deploy: true
  products:
    argocd:
      deploy: true
    metallb:
      deploy: true
      ignoreDifferences:
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: addresspools.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
    ingress-nginx:
      deploy: true
    sealed-secrets:
      deploy: true
    external-dns:
      deploy: true
    private-external-dns:
      deploy: true
    cert-manager:
      deploy: true
    pihole:
      deploy: true
    cloudnative-postgres:
      deploy: true
    authentik:
      deploy: true
    longhorn:
      deploy: true
    sealeo-temp:
      deploy: true
    harbor:
      deploy: true
      targetRevision: "add-harbor"