homelab:
  deploy: true
  dnsResolverIp: 192.168.178.251
  products:
    argocd:
      deploy: true
    metallb:
      deploy: false
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
    ingress-nginx:
      deploy: true
    sealed-secrets:
      deploy: true
    external-dns:
      deploy: true
    private-external-dns:
      deploy: true
    cert-manager:
      deploy: true
    pihole:
      deploy: true
    cloudnative-postgres:
      deploy: true
    authentik:
      deploy: true
    longhorn:
      deploy: true
      ignoreDifferences:
      - group: "apiextensions.k8s.io"
        kind: "CustomResourceDefinition"
        jqPathExpressions:
          - ".spec.preserveUnknownFields"
    sealeo-temp:
      deploy: true
    harbor:
      deploy: true
      ignoreDifferences:
      - group: "apps"
        kind: "StatefulSet"
        jqPathExpressions:
          - ".spec.volumeClaimTemplates[].apiVersion"
          - ".spec.volumeClaimTemplates[].kind"
    cilium:
      deploy: true
    prometheus-crd:
      deploy: true
    prometheus:
      deploy: true
    gitea:
      deploy: true
      ignoreDifferences:
      - group: "apps"
        kind: "StatefulSet"
        jqPathExpressions:
          - ".spec.volumeClaimTemplates[].apiVersion"
          - ".spec.volumeClaimTemplates[].kind"
    gitea-pipelines:
      deploy: true
      namespace: gitea
    tekton-pipelines:
      deploy: true
    buildkit:
      deploy: true
    descheduler:
      deploy: true