homelab:
  deploy: true
  products:
    argocd:
      deploy: true
    metallb:
      deploy: true
    ingress-nginx:
      deploy: true
    sealed-secrets:
      deploy: true
    external-dns:
      deploy: true
    private-external-dns:
      deploy: true
    cert-manager:
      deploy: true
    pihole:
      deploy: true
    cloudnative-postgres:
      deploy: true
    authentik:
      deploy: true
    longhorn:
      deploy: true
    sealeo-temp:
      deploy: true