homelab:
  deploy: true
  products:
    argocd:
      deploy: false
    metallb:
      deploy: false
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: bgppeers.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
        - group: "apiextensions.k8s.io"
          kind: CustomResourceDefinition
          name: addresspools.metallb.io
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
    ingress-nginx:
      deploy: true
    sealed-secrets:
      deploy: true
    external-dns:
      deploy: false
    private-external-dns:
      deploy: false
    cert-manager:
      deploy: true
    pihole:
      deploy: false
    cloudnative-postgres:
      deploy: true
    authentik:
      deploy: false
    longhorn:
      deploy: true
    sealeo-temp:
      deploy: true
    harbor:
      deploy: false
      ignoreDifferences:
      - group: "apps"
        kind: "StatefulSet"
        jqPathExpressions:
          - ".spec.volumeClaimTemplates[].apiVersion"
          - ".spec.volumeClaimTemplates[].kind"
    cilium:
      deploy: true
