homelab:
  deploy: true
  products:
    argocd:
      deploy: true
    metallb:
      deploy: true
    ingress-nginx:
      deploy: true
    sealed-secrets:
      deploy: true
    external-dns:
      deploy: true
    cert-manager:
      deploy: true
      targetRevision: 'add-cert-manager'