homelab:
  deploy: true
  products:
    argocd:
      deploy: true
    metallb:
      deploy: true
    ingress-nginx:
      deploy: true
    sealed-secrets:
      deploy: true
    external-dns:
      deploy: true
    private-external-dns:
      deploy: true
      target-revision: 'add-private-external-dns'
    cert-manager:
      deploy: true
    pihole:
      deploy: true
      targetRevision: 'add-pihole'