---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-token
  namespace: gitea
spec:
  encryptedData:
    token: AgChEGyDQC7w/Y44epTLSWuPBT22eulmePh/ULM0XneQPTBl0tKuqnXbgTe0rYHEq1qevLnOT1FJjdYBwc0M4ki40C3eH4kAyaUJuHG7GY4uQDWfK70FsYRoAl882F8SaGM31wGFwyXEYRq3mOTH7cg6IxVGhjVmgsL/l1249Yj89BbQiBZAN2CHr8XYPXC911Rwi8V1ULPUIZZizzYZhVBz+ljTq+hUKiZdFwEKKovSJl/71CKXUffYxtPwr7PK8XlyRHNmvADDoPIPicnFifK6jwH6Fc1rnBd3VBER4olS6UlS8XnA9VOcHQtIr4z+Si92TS4edwTI/45nbXXtmsIsnNqnMmhfF5wukNrj0bP2vuIR7iQF7AloKJURVzuV2gccUIpAzMzaG5HFatPMIcpCHNl+BnjRW248PBRMWeDJdCxrz85k/lemWNTRiDYqby9mX7lXe9DMncn8i4f3Bn8F7fLRf7nEsZDdVmj7f7PTt49vY7FUK+ljSY5rEfUBO38LnTpOg0UDSI6Aq717XLjoxfR8bajpBe85uGzryewuV7ClXs7tjoU0kNL+zta6fTGnPSimAWMhfOOXVelNBP64kK0y++Nh/9cyG8D9XYpKZgMtOR82mZzQMX+6ZGx4YCX4LwVPxdm5dpC54dXni3jiz+C4xiBPFrafiQg1bzUHE3NgD4PiGvdVYwBd0H9Yjeo5Q3UwChe9aKYWi8ha2k+ApEC75TYqDoxtksR54CfFaT4SVidRgM1U
  template:
    metadata:
      creationTimestamp: null
      name: gitea-admin-token
      namespace: gitea
    type: Opaque
