machine:
  certSANs:
    - 192.168.178.164
  features:
    hostDNS:
      enabled: false
      forwardKubeDNSToHost: false
    kubePrism:
      enabled: true
      port: 7445
---
apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 1.1.1.1
  - address: 1.0.0.1