pipeline:
  name: main

tests:
  enabled: true
  minimumCoveragePercentage: 80
  executeMutationTests: false
  minimumMutationScore: 60

containerRegistry:
  enabled: true
  repositoryName: bingo
  npaTokenSealed: 

chartRepository:
  enabled: true
  name: LuukHorsman/charts
  revision: main
  npaTokenSealed: 

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []