apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gitea-cluster-app-database
spec:
  name: app
  owner: app
  schemas:
    - name: app
      owner: app
  cluster:
    name: gitea-postgres