apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.database.replicas }}
  storage:
    size: {{ .Values.database.size }}