{{- range $pipeline := .Values.csharpPullRequestPipelines }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $pipeline.name }}-csharp-pr-pipeline
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitea-project
  source:
    repoURL: https://github.com/LuukHors/homelab
    targetRevision: HEAD
    path: products/pipeline-charts/csharp-pr-pipeline
    helm:
      valuesObject:
        pipeline:
          name: {{ $pipeline.name }}
          npaTokenSealed: {{ $pipeline.npaTokenSealed }}
          giteaSshPrivateKey: {{ $pipeline.giteaSshPrivateKey }}
        executeTests: {{ toYaml $pipeline.executeTests | nindent 10  }}
        updateDockerImages: {{ toYaml $pipeline.updateDockerImages | nindent 10  }}
        updateChartRepository: {{ toYaml $pipeline.updateChartRepository | nindent 10  }}
        ingress: {{ toYaml $pipeline.ingress | nindent 10  }}
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 10m
---
{{ end -}}