apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitea-project
  namespace: argocd
spec:
  sourceRepos: 
    - https://git.internal.sealeo.io/*
    - https://github.com/LuukHors/homelab
  destinations:
    - namespace: gitea
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding