---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin-password
  namespace: pihole
spec:
  encryptedData:
    admin-password: AgATSckLTIgaKB+hFdrQhYrB1L8rsmWYbq2DlI3SV/+6UFFKF9hbY4ILHVE6LMZXV5TPjUh1zEYRbO6czCsOXAlf6o9dPZlBtLhw34Re6IFUknc3yNxsYQHXdCtybhNLZfBTmRkCXV7u0zX9i+PgS0OsjrHtOwVQuAgQES7MzE58Ib7WmS83YRss9jcmjEGEZTc2V7e1Qr5fD0iKZgrokQgvPGMQCIQq2CKXpj2pp4wAwWHQ/exG1FwTABP+yVTPc9qo5+bDhxKo33VrFmXl5+x0AwCguY+5gdYF8tQg0E0w5O4X9ikH9w2GZt9bCW09wJjaCH2gN9kQDtbXLizyg6RbBhEYXfLXMvQWxhxvcFPAwxSaGuCDbdLsyNOL0+xpe+djIXYR/cyT1SzwtHTo8SANv3FDkpsw6j8RmP0kNoIHvoYSu2L+cQBMhU8Bh8PJrESksdCxxMsyuuuZ5rVlEq56IZMVelXg1i5PehQAE0MOsY6qst5aVIRq9bbUDUcsSnkDk+DiwaJTICGZoXe/0+YOO66KsN+HU48fkRlCM89AdaZvswizsZUusoSaOGLbazV1UcS1CVDnmlVKnIUIoNgDwqjT2GVJgxzZg8auQOsF9vmvUw2pyYNaoZy81+r1cQsgKqXViEziD2h6UqtpSz57hwrj/DnFycI7/E09EmV9wKxhgNt4gWWa/EXnZZ4p4X3xhVnVsszJRSsxMNPJ1Uflie5s8vRGE39uikvxtjuw4JW3TGfsKf6KLN/uoW+seL0CLQ==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin-password
      namespace: pihole
    type: Opaque
