---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin-password
  namespace: pihole
spec:
  encryptedData:
    admin-password: AgCfs2Kho1yFPHSI+4xxAwMoh3HyJgzvgTAMH7HYWp99Y27mH3/yDegzCUbBskSGmQBaI6O4vFpawiGeKdEJ9ZNMvp5C6JWPDlbyxl4On8EZXLA+Zez2SbQl+ZERaXjavt7orqkMG04cNuZja22fqkWReizDI9QixUhl+0Mu1nfK1M/sFWz4G+qByHGaVP+ww8mhdPFVrrsldwgura04ry0zf6vK4l7oEn5YPUoBqt9rciboIqbyEsOV3Tuh+a6WUf4OPPut7GEBgXPXM+dguFkLWc9afV2PnGMvBRs2jlnldeMLWEFBIibJQ3rQ/lCLiQNM7wo8bXKX3fpOJZ+r97KNkQ/jxtpe99W8lpePLzD5YC6M56c0ARiexDNLEcl/Pa3MeI1hbvM31Xkt/OpOx09cK88FPpBLev1bwKhdAGQLr6AYmZCZOeh83U4mEmCqZ3tjiHQ9viKBGCZ/K1VguHSmlnlYekb0ALWpzm4WHWemXznfxhJJ+cna0n72xMZJCSCq2pjXtzjXmG8YqKlaH6XUWuFcsG8KUlwhR6/e+O7ffjRSKB7N8HCANN9BtJX1Nl3jgp70Yq5nlSmjHbCPmnbh6jRO6naBbyRk3jyhd9CMLi4z7zF+Vw55JfVHSMFFPw7IM+lQaQYoK+KnbBkjxQM9gF10F8jacCYGHi62/E5rwYMyhzgQmorlG3nYvvSOjM2HjFq00I7dAp6IlPmKlOfPlETfSn15IbL4FHc0+JHOZdTPVmQtky8kPanyYx55gGC9Kg==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin-password
      namespace: pihole
    type: Opaque
