apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-password
  namespace: pihole
spec:
  encryptedData:
    admin-password: AgBD98waibvoIuSaUujNKKtzYFwl8gHGh8Xvc4r2roxUjdz876qi9CHU5BS69LuLmyafd8chVPeAuRSzg9GFnzktBC8gg1M+Uhrx59uorjcGaVeN2dcjfmyichlsAmEmgOy/3ULybXk61e+rYsK7Ny9dvrFP5sfs0OS2DbNJJURHeU5+46h/lMlC7thSITvbaxOCZ3TZ8tMCliCpxSOzCZkjI1sGEj9OS1KSwBv5FvoYNb4EnpKv7MXlETCGRIqOBlQeZQIMs9/wjihiZ93ZE7gvKv5puYOrsY79bMkiIMzhNQJo3JlHw8k/CELyJ5i7a0hatdyFBxU1LaTLEOfO2Vp045CGW8A3ltd0s2FWua20hirC19ASQFYDmp80kvapgVBi7eXsgioiSLdeV5vGLKqEDrNN+6yoDkHhASiDsuszilKdpHWRL7d10yOg/2OLSVzwNT/eNrkxKWE1WjXH3FL+CzInSkL0PJ0QwEVYdwvXif/pd4oDlI7ad7pmdgvVP0y13ikaO0+wtFQMAWdC33hlB6u23u6EKjTvKWQJEv8TC0kKtnhaS97XcdXbsWzcZkgVU5Ahcw0aKtHLjgk9IEsKieqA7PsHYfD+dLgqO8luFTPw7vDUYOHN72lUQ/+zBRkp7AWpOZGAQeNeqYM5qwzaydixiNHjkn6cLOtRr41u3f0N21ONawkL2UOoMOrY26/itmDYRg3MEdY8zGcSmOJVXlxYcxOVehLoUfkRI+M7x7n6Hs3H293kBb5j5VXxab3bIQ==
  template:
    metadata:
      name: pihole-admin-password
      namespace: pihole
    type: Opaque