---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgBgRum6yY9Ii7thLz1PTec4g/UCiNV7kqpEvu3pBXBPD2SK8sGPg0+5jPr3S7E+4/S0LBLnN4uHtRrGqK0q70AqSNPrVIdeTd7J5fH8LIfKUsIIloWHzBLxkRmzVESSiWhvDh9b96SqVCH6rkEU7XSg9fW8NOPx4EfpdDBhhxMdVukgfpZSdvAgbf6hRgZm1hbOpjRQRUJfCK3EtCOusXuE20Jp+W3Oze0wwJg5flNmE3ZQI2yFsKj7uoQfmsVKK+/JOHyQloYP05ezqQLemZSE/eZghgCL7gZMGlMLny3uz6JsIFGRmDhW9yIvL5oyhhxiqJEfJMhLcB4KeNNiiB07ZX/g9KENVRdbOUtTUg/GVwIwFryNKYgnI9l2OuyZRZvue1BdXoKvDsaqJU0P8ggO1y4NXubrT7X3aYWM4uE+/ETC8Axw2945jLS3b9XEzFhXkIimFsKHJBK62wQem/QqEbXLbXMBrW3d3EBiVDiKwI6vIQ5i4v7kMhkU5wEej+8UV80AniGC8X6MuSoqxHXo1AGQtqhlE1lEhLOjgUVhe3T3ee4LXjgseNJDynwX38of+bfqsLtlUJhO+S0cCPEdTXc1wKuhsC0/pg7ocAncOJnQEnu0SL5c727KnU2qXCxyb0vB78ameuCL+WynzIvez1WgrZj46bgL0Su4WKdPDwPZIgvt7t7GYYimvmYHaghRRt1z2sa0mAf1rIFfh49O+HyVEw8B6NxOapHIHYbKrq3ecdtLZK/p
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
