apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAI2G1Z39e1m+nsZc37xhYyA4R81ahipDZneXG6TLEhcRlAeFGYKkv1/4PK0i3R0pa//BJRP+aHV4HhGmIxW1O9nkaAvQXfvhvfiXa2j5zksTXuJj4fy6RGqy42d/tTMYLdVISPZ9UnAaI+v9gNXyyE8sJZMZVFgPANXxfZE70yxtBLO2m3y9s4Xn3jL3Eq1kVvbGSc0lj9J/K90kxB16JXPzJOybVKuq2D9RkQOmIiAofN/rbLWrYMP3DFlZCDEJ4tRYWgDFUqVwSQiN4QI23GhL4di+Qp5w0teDT/Z2Dat3sCgm4QXkUj+Z+j9zga3XgB5KqmPhVmmbXXTKF/oHsgOxFucuRB0zTExHpj/0ZKZEaYsfvsAhaTI1Gu/lKwvqrJ9Y9PFKPPac8XzU9QBxYPXeeTknTCb1p42hbKOVDmwhUXt+2I8b1yn5rfzRKP7vVFB36gYCcJqVORduGDCw0lkfem+MERVT7k5A5JHUbtPEL/qdR5wAGCyYSxL5CusNJ43Z7emMX7LLsu9WxOMJp1nT5WDLFBAk/soUz6FBs0jKX3WECY+RhTzCNXxF+DJF9uZK5/ziepINGqUoorBGRi3c/ZSDZacgwc3b1b2Xz/AeQnDCAbThTCw6GO+Eo1Dct2eLXpFCl8P1g/vKjKNwUk5yjERJ/ckCI+LGUskw6NiXhaQo3orlmDeZfcvPxbV3ivlbRuKB3fWqR+Y0stZ3490ZulLF5Y0eT70J9ekziC0zORdfukGSpg
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque