apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgChoK5JemEkdWgk1lI2azLBm4Stlo01LXYlYBwAC/PKk52cdVub9Qr7REWO+vC7u/dPOQfnW8dSArUsmLJuiLm3MtKZAw8gTalJxJ2GzrBcVAIqNiKT4qTCiMQcoMuBtt//BgtuFuhtThEKN/BXG22LBmW+3dxHWVX8XW8dnvHhP2MuMDUSE3RxvjsTzyyNoAT3vA//KMyek9sRwZV6AcHcfsacGYYKgt8whUGycQT2l956WTQSbr+oG77Lp8i4XqHau1FsWiMjxFMcyHPZNuUO8a/6FGjLykOO0rnVdinXL54f2hQyUegzRdaXk+F4H6g0qPJa5dTBT1cg+xQfn6itxoGceOOXYa7EbGJhv+91R7yQp8ePAyY8hIw0/bL44QEbz5VFFRMYgh02cE5UYtkm+68QpeV2l4pymsrCdva+0exmt31SoPPYLVArPSkJUBFu5fEMYFWagR/t9T4xa8CIi6pXwPaKy77etyL/7DCUflTV/sCOvFyAwsnNg4Hh/o9okrlBTLMkzq9/6HE3WM8/lY91TrIc6/t6J+thGJxaUh+sjelVYdinVxR8U/fD0fLRvvYc4FfdqHkIxZDfoVuAwIPCzADAA+xGYeyICkH/L5234ZQIPd1sBcjvmoWlQq90LG0iCqFyD3BmqR4roeRtxZ49oQxvSgOCw7d68BabUVa+4ydO+K6sDJljwVEK/Rc=
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns