database:
  clusterName: authentik-postgres
  replicas: 2
  size: 16Gi

authentik:
  global:
    revisionHistoryLimit: 0
    env:
      - name: AUTHENTIK_SECRET_KEY
        valueFrom:
          secretKeyRef:
            key: secretKey
            name: authentik-secret
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: authentik-postgres-app

  worker:
    replicas: 2

  server:
    replicas: 2
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
      hosts:
        - auth.sealeo.io
        - auth.internal.sealeo.io
      tls:
        - secretName: authentik-tls
          hosts:
            - auth.sealeo.io
            - auth.internal.sealeo.io

  authentik:
    log_level: warning
    postgresql:
      host: "authentik-postgres-rw"
      name: "app"
      user: "app"
      port: 5432
    redis:
      host: "{{ .Release.Name }}-redis-master"

  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
    master:
      revisionHistoryLimit: 0
      persistence:
        size: 16Gi