{{- if and .Values.updateDockerImages.enabled .Values.pipeline.giteaSshPrivateKey }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-csharp-build-and-push-images
spec:
  params:
  - name: branch
    type: string
    default: main
  - name: repository
    type: string
    default: LuukHorsman/test
  workspaces:
    - name: gitrepo
      mountPath: /workspaces/git-repository
  steps:
    - name: git-checkout-branch
      resources: {}
      volumeMounts:
        - name: gitea-ssh-private-key
          mountPath: /var/.ssh
      image: alpine/git:v2.49.0
      script: |
        mkdir -p /root/.ssh
        cp /var/.ssh/id_rsa ~/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        
        ssh-keyscan -p 22 gitea-ssh.gitea.svc.cluster.local >> ~/.ssh/known_hosts

        echo 'Cloning repository: $(params.repository)'
        echo 'Cloning branch: $(params.branch)'
        git clone ssh://git@gitea-ssh.gitea.svc.cluster.local/$(params.repository).git -b $(params.branch)
        cp -r test/ $(workspaces.gitrepo.path)
    # replace test/ with the actual repository (not full) name.
    - name: find-and-build-images
      resources: {}
      image: quay.io/buildah/stable:v1.40.1
      script: |
        shopt -s globstar
        for file in $(workspaces.gitrepo.path)/test/**/Dockerfile; do
          dir = $(dirname "$file")
          echo "Processing $dir + $file"
        done
  volumes:
    - name: gitea-ssh-private-key
      secret: 
        secretName: {{ .Values.pipeline.name }}-ssh-key
{{- end }}