{{- if and .Values.updateDockerImages.enabled .Values.pipeline.giteaSshPrivateKey }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-csharp-build-and-push-images
spec:
  params:
  - name: SHEBANG
    description: |
      Python path. Depends on the image.
    type: string
    default: /usr/bin/env python

  volumes:
    - name: gitea-ssh-private-key
      secret: 
        secretName: {{ .Values.pipeline.name }}-ssh-key

  steps:
    - name: git-checkout-branch
      resources: {}
      volumeMounts:
        - name: gitea-ssh-private-key
          mountPath: /root/.ssh/id_rsa
      image: alpine/git:v2.49.0
      script: |
        git clone git@gitea-ssh.gitea.svc.cluster.local:22:LuukHorsman/test.git
{{- end }}