{{- if and .Values.updateDockerImages.enabled .Values.pipeline.giteaSshPrivateKey }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-csharp-build-and-push-images
spec:
  params:
  - name: SHEBANG
    description: |
      Python path. Depends on the image.
    type: string
    default: /usr/bin/env python

  volumes:
    - name: gitea-ssh-private-key
      secret: 
        secretName: {{ .Values.pipeline.name }}-ssh-key

  steps:
    - name: git-checkout-branch
      resources: {}
      volumeMounts:
        - name: gitea-ssh-private-key
          mountPath: /var/.ssh/id_rsa
      image: alpine/git:v2.49.0
      script: |
        cat /var/.ssh/id_rsa
        mkdir -p /root/.ssh
        cp /var/.ssh/id_rsa ~/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        
        ssh-keyscan -p 22 gitea-ssh.gitea.svc.cluster.local >> ~/.ssh/known_hosts

        git clone ssh://git@gitea-ssh.gitea.svc.cluster.local/LuukHorsman/test.git
{{- end }}