{{ if and .Values.updateDockerImages.enabled .Values.pipeline.giteaSshPrivateKey }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-csharp-build-and-push-images
spec:
  params:
  # - name: containerRegistryUrl
  #   type: string
  #   description: Container registry url.
  # - name: project
  #   type: string
  #   description: Name of the project that the images will be build in.
  # - name: globPath
  #   type: string
  #   description: Glob pattern to find the Dockerfiles.

  - name: SHEBANG
    description: |
      Python path. Depends on the image.
    type: string
    default: /usr/bin/env python

  volumes:
    - name: gitea-ssh-private-key
      secret: 
        secretName: {{ .Values.pipeline.name }}-ssh-key
    # - name: docker-config
    #   secret:
    #     secretName: $(params.pipelineName)-buildah-docker-auth

  steps:
    - name: git-checkout-branch
      resources: {}
      image: alpine/git:v2.49.0
      script: |
        git clone git@git.internal.sealeo.io:LuukHorsman/test.git
      volumeMounts:
        - name:
          mountPath: /root/.ssh/id_rsa
