{{- if and .Values.updateDockerImages.enabled .Values.pipeline.giteaSshPrivateKey }}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-csharp-build-and-push-images
spec:
  params:
  - name: branch
    type: string
    default: main
  - name: repository
    type: string
    default: LuukHorsman/test
  steps:
    - name: git-checkout-branch
      resources: {}
      volumeMounts:
        - name: gitea-ssh-private-key
          mountPath: /var/.ssh
      image: alpine/git:v2.49.0
      script: |
        mkdir -p /root/.ssh
        cp /var/.ssh/id_rsa ~/.ssh/id_rsa
        chmod 600 /root/.ssh/id_rsa
        
        ssh-keyscan -p 22 gitea-ssh.gitea.svc.cluster.local >> ~/.ssh/known_hosts

        echo 'Cloning repository: $(params.repository)'
        echo 'Cloning branch: $(params.branch)'
        git clone ssh://git@gitea-ssh.gitea.svc.cluster.local/$(params.repository).git -b $(params.branch)
    # - name: asdf
  volumes:
    - name: gitea-ssh-private-key
      secret: 
        secretName: {{ .Values.pipeline.name }}-ssh-key
{{- end }}