apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-eventlistener
spec:
  serviceAccountName: {{ .Values.pipeline.name }}-eventlistener-service-account
  triggers:
    - name: {{ .Values.pipeline.name }}-listener
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: cel
          params:
          - name: filter
            value: "body.action in ['opened', 'reopened', 'synchronized'] || body.action == 'closed' && body.pull_request.merged"
      bindings:
        - kind: TriggerBinding
          ref: {{ .Values.pipeline.name }}-triggerbinding
      template:
        ref: {{ .Values.pipeline.name }}-pipeline-template