apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.pipeline.name }}-eventlistener-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.name }}-eventlistener-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.pipeline.name }}-eventlistener-role-clusterbinding
subjects:
- kind: ServiceAccount
  name: {{ .Values.pipeline.name }}-eventlistener-service-account
  namespace: {{ .Values.pipeline.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles