---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.pipeline.name }}-gitea-admin-token
  namespace: {{ .Values.pipeline.namespace }}
spec:
  encryptedData:
    token: {{ .Values.pipeline. }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.pipeline.name }}-gitea-admin-token
      namespace: {{ .Values.pipeline.namespace }}
    type: Opaque
