{{- with .Values.pipeline.giteaSshPrivateKey }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $.Values.pipeline.name }}-ssh-key
  namespace: gitea
spec:
  encryptedData:
    id_rsa: {{ . }}
  template:
    metadata:
      name: {{ $.Values.pipeline.name }}-ssh-key
      namespace: {{ $.Values.pipeline.namespace }}
{{- end -}}