{{- if .Values.updateDockerImages.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.pipeline.name }}-harbor-robot-account-credentials
  namespace: {{ .Values.pipeline.namespace }}
spec:
  encryptedData:
    config.json: {{ .Values.updateDockerImages.harborRobotCredentialsSealed }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Values.pipeline.name }}-harbor-robot-account-credentials
      namespace: {{ .Values.pipeline.namespace }}
    type: kubernetes.io/secret
{{- end }}