apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-pipeline
spec:	
  params:
    - name: gitea-url
      type: string
      description: The Gitea repository URL
    - name: sha
      type: string
      description: The commit SHA for Gitea status updates
    - name: branch
      type: string
      description: Branch of the pull-request that is requested to be merged
    - name: repository
      type: string
      description: Name of the repository
  tasks:
  - name: set-initial-status
    displayName: Set Gitea status to pending
    description: Sets the Gitea status of a specific commit sha to the pending status.
    taskRef:
      kind: Task
      name: gitea-set-status
    params:
      - name: GITEA_HOST_URL
        value: "$(params.gitea-url)"
      - name: SHA
        value: "$(params.sha)"
      - name: STATE
        value: pending
      - name: TARGET_URL
        value: https://tekton.internal.sealeo.io/#/namespaces/gitea/pipelineruns/$(context.pipelineRun.name)
      - name: DESCRIPTION
        value: Acknowledged pipeline run by Tekton
      - name: GITEA_TOKEN_SECRET_NAME
        value: {{ .Values.pipeline.name }}-gitea-admin-token
  - name: build-docker-images
    displayName: Build C# Docker images
    description: Building all C# docker images in a repository
    taskRef:
      kind: Task
      name: {{ .Values.pipeline.name }}-csharp-build-and-push-images
    params:
      - name: branch
        value: $(params.branch)
      - name: repository
        value: $(params.repository)
  finally:
  - name: gitea-status-failed
    displayName: Set Gitea status to failed
    description: Sets the Gitea status of a specific commit sha to the failed status.
    when:
    - input: $(tasks.status)
      operator: in
      values: ["Failed"]
    taskRef:
      kind: Task
      name: gitea-set-status
    params:
      - name: GITEA_HOST_URL
        value: "$(params.gitea-url)"
      - name: SHA
        value: "$(params.sha)"
      - name: STATE
        value: failure
      - name: TARGET_URL
        value: https://tekton.internal.sealeo.io/#/namespaces/gitea/pipelineruns/$(context.pipelineRun.name)
      - name: DESCRIPTION
        value: Something went wrong during the pipeline execution
      - name: GITEA_TOKEN_SECRET_NAME
        value: {{ .Values.pipeline.name }}-gitea-admin-token
  - name: gitea-status-succeeded
    displayName: Set Gitea status to success
    description: Sets the Gitea status of a specific commit sha to the success status.
    when:
    - input: $(tasks.status)
      operator: in
      values: ["Succeeded"]
    taskRef:
      kind: Task
      name: gitea-set-status
    params:
      - name: GITEA_HOST_URL
        value: "$(params.gitea-url)"
      - name: SHA
        value: "$(params.sha)"
      - name: STATE
        value: success
      - name: TARGET_URL
        value: https://tekton.internal.sealeo.io/#/namespaces/gitea/pipelineruns/$(context.pipelineRun.name)
      - name: DESCRIPTION
        value: Completed pipeline run by Tekton
      - name: GITEA_TOKEN_SECRET_NAME
        value: {{ .Values.pipeline.name }}-gitea-admin-token
  