apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  namespace: {{ .Values.pipeline.namespace }}
  name: {{ .Values.pipeline.name }}-pipeline-template
spec:
  params:
  - name: gitea-url
    description: The Gitea repository URL
  - name: sha
    description: The commit SHA for Gitea status updates
  - name: branch
    description: Branch of the pull-request that is requested to be merged
  - name: repository
    description: Name of the repository
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: {{ .Values.pipeline.name }}-pipeline-run-
    spec:
      pipelineRef:
        name: {{ .Values.pipeline.name }}-pipeline
      workspaces: 
        - name: gitrepo
          emptyDir: {}
      params:
      - name: gitea-url
        value: $(tt.params.gitea-url)
      - name: sha
        value: $(tt.params.sha)
      - name: branch
        value: $(tt.params.branch)
      - name: repository
        value: $(tt.params.repository)