apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: {{ .Values.pipeline.namespace }}-triggerbinding
spec:
  params:
    - name: gitea-url
      value: $(body.repository.url)
    - name: sha
      value: $(body.pull_request.head.sha)