apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-secret
  namespace: private-external-dns
spec:
  encryptedData:
    pihole_password: AgAoXw4bFgRTZSxpOPFm+OExSF29pqa4zFGsNbXahl9jc+YMzzzYwTvp09ZSgCddq8nG4PFItVoTeuUG7wiPIvDGzxHA6f+7QLsMt6a+cI48Ayp5kNRXHOgnqo8WfFKRyIw4GxckA2f1+BPPmt3aKNRrVbJUGzGNB8S9KZ6OHtEZAvaWW4rtnWA0J1UTjPFMaewFCXnglh0/5Svdl4kv00H6sFC25mGzV/kczfpnLRXTTV+KpHIp9tt1FSsKn2jBNbQcnk2FXAAK23WrFVoCNlvlusWMNjEY3pyqGUXlpOIdUNNN2CgNbf5ysX1zgHEfcza3aH7WOuIOzK9Q0T3x57NAT6QvMSYGOysvynfkOjycdR8aHJiikPX6Os1PBr2/K37TBNF9qYUbDG7GTZICakGf+CGMWyJcmQPCknhDoXOnHCcl1VE2KRY18vTe/ljJ602//D2Ii0WvYOefsAjLKapV3zKgZssp2/gRUFOSsv+iv7s77VwVmnqZQC65ZQPqHcLVA1ceSIvndZGsuhAbPPiwFW5ie8yicqEgFMArypaOFHOy2YKjFmVFFi/65O3Qs48MIVEJXM4QBa63IVmS53Wm0XzEPIkFEyJTMa3iRflaeXjDYgMTrImmxpzNDF672ahe1DnxcSLW9wZlUI87+y8bhuMZ+I9GIqJgK8j51I+2GUxe+mq9iwBICBvRI5ZVHOafybJA5ioIcRFaLA1UqX3JperKWW1oBTQJ/fQKwH1G+c8h03NqO8/tCfp7X90cfRC/dA==
  template:
    metadata:
      name: pihole-admin-secret
      namespace: private-external-dns