---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-admin-secret
  namespace: private-external-dns
spec:
  encryptedData:
    pihole_password: AgBYteSVZlPFHLHN3qGfiAIhir3V8mBE37PH3+0yTtzHgpoaq/Th8iHg9hiqZPg/POvt+LgnzDUAlOHdzL2Ihk7fwJJFjcNVdyQkyTFXdD8HyOr8bujUpcf7TwAMBMuRSteMS8hXKRTRVHJL/3PffqPLEFpJMzYReHHdW66y22sq04eBoJngPUQFOwNFHmM5D4EGxULDG+WRfxfjOmfOCkNJo9pIHffEy/E03H5u1V2kG4gfOIgXjzMrDA9rtEcMZXomXHKgP2alYLrusO4K6mjv9gX0eYxb60CRLn1lRVzqVpaRMnM1yyydMJh8YDqlUHJOUiVHrK2obME0mb6IemxodlO/31ted9KLqqtIeciVCfE8TX7bp+T8FZX3KGsS48B7tMPb1etPQ+Hw9vrcRKiv5zMSQ3yTzSUkvNJ1Q34LUsXLWNFENGV2O2j8GJweogzgu/L8tePRcCtdJT2jyihTHq/1OZrPT9mZo68iLVAMzTSiTEVzQvfy7gatTLh9ha1wAiyvxKPP24lBQZyD1Hq3VCQG21qsD5a7T+bte6VvZ+tAFMh4sI7rjcqpgj4sCwwtARrkgsVTsNlbXOb8ejW803syU75H9mrvOA/LYxcun9dk2iw4LzIFALLdc885ANkWvhP5pOJ/BAzdkeWM4andQJfkw81PKF0um4fZZj6u8aIDXYmooYRByAgZ9znrHbLad64ftbBwiDpybBpLgQVyHVFGqoA07YDuEBvCV8P/y8qiCWYTyWWO2LEKNXqolNIlDg==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-admin-secret
      namespace: private-external-dns
    type: Opaque
