apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole-admin-secret
  namespace: external-dns
spec:
  encryptedData:
    pihole_password: AgATl0wWMc+jwegkeq9waLHZuCi//3+PPhlScB8g0WJdSOniwRXzb/kkJ3cNrLjKI6e65Ac5SeJ6JPQO1fdZ1k/Pl32tC6iwbkbzXlDaqWXlfzA0ltQoUIikLBUC63IJH1M4m0JHi7Mj8fbI2/VVDUtYlFgqEnJMGzM7tTP/h8MMLIm7k17NVeGPqVRxl2eVoSgw/gGlJt7LqUxA61eAlIFdtBCYpWos0cYOE/6JVs+Utl/gLbjZXygJyVoAnuj2WQRgplHWcEV6hw7C8ZGhLj9zqMx0+b6dxvn4LipIjG6C/QUd2XCdC3cPGMkK6y0PlhG04FbBNj8d7+QJ/JXtH95SG0WkC2Cq8FSGWynSqBxLSxLblLdxSgmy3EX3+gbr07KX7QIDZi7o0Wg3P7xQQZJj5d4TLcrRXpWIWa149fG9oMt67ywBSiO7sCiq5hMeAVMXgR0Ofu3OgLX40h5eaTBgeHeSu1kzFTbYXj1Y4za/k+JBtI/c51/4o1NzguTbomwN7V3gbLBp25Mi6B+d2m3Opf9KaK60w0l1UAynOU/8hznspYcCQZIsta0KFgDBCLKq3ORXSI8cuav8bM+R49vrAWQWj8Us4NIDVnp8t2IanQff1M3DOSs7EBLf/u82xfajDDgQFguTwrCmRxWocTlweZLC1vycrKzVHbrqZK47JkHyGhyqwRDBmunnUjUBsUrgTszlK4UqS3mr7WvGmstgcvRlyf4NtTLtDRp0yA0vksA77toOaaHY/2ZBuNlWpcxClw==
  template:
    metadata:
      name: pihole-admin-secret
      namespace: external-dns