pihole:
  replicaCount: 1

  extraEnvVars:
    FTLCONF_dns_listeningMode: 'all'

  serviceDns:
    mixedService: false
    type: LoadBalancer
    port: 53

  serviceWeb:
    http:
      enabled: true

    https:
      enabled: true
      port: 443

    type: ClusterIP

  virtualHost: pihole.internal.sealeo.io

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: 
      cert-manager.io/cluster-issuer: "letsencrypt-dns"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    path: /
    hosts:
      - pihole.internal.sealeo.io
    tls:
      - hosts:
          - pihole.internal.sealeo.io
        secretName: pihole-web-tls

  admin:
    enabled: true
    existingSecret: "pihole-admin-password"
    passwordKey: "admin-password"

  DNS1: "9.9.9.9"
  DNS2: "1.1.1.1"
