apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitea-pr-pipeline
spec:	
  params:
    - name: gitea-url
      type: string
      description: The Gitea repository URL
    - name: sha
      type: string
      description: The commit SHA for Gitea status updates
  tasks:
  - name: set-initial-status
    displayName: Set Gitea status to pending
    description: Sets the Gitea status of a specific commit sha to the pending status.
    taskRef:
      kind: Task
      name: gitea-set-status
    params:
      - name: GITEA_HOST_URL
        value: "$(params.gitea-url)"
      - name: SHA
        value: "$(params.sha)"
      - name: STATE
        value: pending
      - name: TARGET_URL
        value: https://tekton.internal.sealeo.io/#/namespaces/gitea/pipelineruns/$(context.pipelineRun.name)
      - name: DESCRIPTION
        value: Acknowledged pipeline run by Tekton
  finally:
  - name: gitea-status-failed
    displayName: Set Gitea status to failed
    description: Sets the Gitea status of a specific commit sha to the failed status.
    when:
    - input: $(tasks.status)
      operator: is
      values: ["Failed"]
    taskRef:
      kind: Task
      name: gitea-set-status
    params:
      - name: GITEA_HOST_URL
        value: "$(params.gitea-url)"
      - name: SHA
        value: "$(params.sha)"
      - name: STATE
        value: failed
      - name: TARGET_URL
        value: https://tekton.internal.sealeo.io/#/namespaces/default/pipelineruns/$(context.pipelineRun.name)
      - name: DESCRIPTION
        value: Something went wrong during the pipeline execution
  - name: gitea-status-succeeded
    displayName: Set Gitea status to success
    description: Sets the Gitea status of a specific commit sha to the success status.
    when:
    - input: $(tasks.status)
      operator: is
      values: ["Succeeded"]
    taskRef:
      kind: Task
      name: gitea-set-status
    params:
      - name: GITEA_HOST_URL
        value: "$(params.gitea-url)"
      - name: SHA
        value: "$(params.sha)"
      - name: STATE
        value: success
      - name: TARGET_URL
        value: https://tekton.internal.sealeo.io/#/namespaces/default/pipelineruns/$(context.pipelineRun.name)
      - name: DESCRIPTION
        value: Completed pipeline run by Tekton
  