---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-admin-password
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBgalZXG8qV6qwXtj+U6xy/iFmieKNhfZApn2KBXCUogGWzrBOXJUUZcldBxww7404kp1hSZNzW/DzhEHQtx1xRt/7Rm20zRyHqPjNRJDn0EZRTm5e857P1KpWGM69/OBHKpY56kEV5wfb1SnxUZkmv0URFL7blBg3+EEauXHNx/+P4z7NwGBv2eL4fmeWDNf7zHv3+8zbvdpt/HiTqiz/YBRBsDwL8tJSR3/SyBGOrXc4znAmw3T7Xwkm/aOW97V1LCr900xLYXf+RuLLxag1q8bOihYo1tl0tf0D4NyywTi8tghfRXeg0bh35TSjq+58RE94+SgEWvWvQmLZZcKUHxxzqAjQQvrbF2dITzd4piPbkFjsTyMIPXNOa5pW4DTu0MgDxl/1Y/bCsSHzmF57THGHsANzaaZ/PovkQgrgZN8MEh8Tr6whwemDDQPzOx4jYL/kjGw8mkAesg1Y2aS3daAkZBK4JeswxWVNbChzApxu1MrLJrshKv8DV+Re8TTj50PfycbPYumgXziRnoCB6DKcLlD4NxH5VMWWyGOnN6jWX1bXXGfYutm3pSYbO+/9LwXfE4rCv36zVUcotZ80FqoCKxJI6hzliJ02D9O3I7VY8lPxKiWqQ84KwVDIB9Q88h1lYETO6yj8tDDL1tyRqA9TR1ksCWcciQwNyWR0EdTpIhin8anpqg8MUZ98l/Atb0DdUggjsqrE5Y9pFtMN36PVc1LmXcHOSjB2PDS3C5F8nzRTsIaWIid7DKL7qCcZKORE=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-admin-password
      namespace: harbor
    type: Opaque
