---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-oidc-secret
  namespace: harbor
spec:
  encryptedData:
    oidcConfig: AgB4MeWvgUVrwyPYPn1w2Mf4ZtrLgM0XGH1cPrP3Ru6Mh7fM2iZJO1TIozBSEN74pdwrtRvzhHl1Tv6a2kJJAdOJJtJmv5Gew8ErDH7Nh8Y/CaHWR6CjRsw0c/aHn/QxNPzYommxp3b1nFmHwZd6fA76ntVfD/SLYGiykFiROjsrghddUllX/ZIxiestM3/IttpdxG+Jp9edBpTWH9zPMxxEtxzF32cReYWHkOOYqWcgJxo4uXf+bWmLtBHdBtGF5MvmPdm5uStDBmqHcXXg0mZMjf2NPsRQm82s2AjJTx5cMC0dMFeyHHofj8R7zeqjWXPW0yKqlLDN6x1AT8Bz6tcOne0ic7WKUJoLg37Bfy8PJ5VheHjYfv5XwRE5hoxOPDt42hCfagBt9nOqU/uZTxqmFZ3UNDgRbFlL7KITZKNchzXzuOPTKygKa5d8OHYSmqbClpx/6aFBi4gkhCqK7zJewVDiZAShykgMw2ykOsnKY+1XIjm7ADfKKGsUaWHombVSBi1gvfhOwWJD9DttL4xsT5L+ZuZCrPrGf42gifP5hJOlUjbyRmW6Q/edHRZBnHOu9R4sj1I1qf8sIxc6n+U+v/KnKTunJhr2zB4zKAbQ/wnPa7z6BKvJxmcxUp5W4+ZGG6bv34YoBiBp+/5HsPR73Y/15uL+j6F8OedicNuu+lM7ek3GkKCV59k0DSArKHhXAGWb9C4L0u7H71AY33pfe4PCoqzmq2VlJeYLlJcNbBsaC644VUoFPYUVGglyRPyDsXkayaSssP3vnydCbfj5omjCfEELCXiYvGQCMiOvfhJXQLjXSqjNF8u+pF3Pdo4LiptDLGVnSfLF73MSopMRcgcgwFr5U4fcY2neojC+i/+5+lCXb6jZb77ZYRFv0ux4VFQRcMVS47O7LKQg3zeDQab01bR/4ObouvLN7ZoSPVc/mOyeIGCrUCq4Es0donYgI3AjselyGW/KOzEZVRo0gJW0I7XffnkRHJ9yEz5crUNA2wom2ZbO6J4IHYHkG07Ro+GB3dNDxcSQk9vNDY55O/qg7NQmYTGYeUBmWw0S97trhwsC/d5/YyKEcbIeb0XCFYqHzquznkj4bwaUdg0W971J34vrhYe0iVYApnIe3z7TyTQUjc2JQZAbOY7Id0Afx3wIzdN+QLH4+/zIpUNL4Q+3eudseqZfl9vU5lZw4I2Ciye6NUKIDY5/T8hYXCVsp0tkvBufsuuX0cLc8mkkskS44NXAXO20h1yv2s/o08fT41rQh71BPKqTBp1ljJwzToFrpysV2wfcZpaoqDM6gqfQnU+OGC6Ab5E0D2Wz5FFpAZw6isXG3aLV7CfmreZQiFhIyvfWlReX1sBHUXNvbGPg6NuJsE3o7DN1CKPNpx5agaJQHuLtkQTHq3catF0QvtOgMIgqWMIgaPa9IUFpETV9ELtrGf7+KiUapc4dI2NzaziyeOy8CYAyPMgoM9V6h63jjupTlz/wwdYdmpDqBYdlD3ZeismlsIdF17cjN4/+Kgg=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-oidc-secret
      namespace: harbor
    type: Opaque
