---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-oidc-secret
  namespace: harbor
spec:
  encryptedData:
    oidcConfig: AgBrjfeiZx69KVAEHHS8ZE4YJogYMIN56/5lxPiGxN3txMhHMxIP3iZCtvURdpLfwmRLyh77lvjJUTguzKlaApXs2y9CnPUccn3iytLP6Ei8cov61IBVkEU4Ln+e6Kq6Rf+ESDl+LmXm6+WzF4endtlAIQ2fHqI3Sz8mAhndSb9rLzkQlA3pw+0vuSPx1cXkjmpvre2CMWOaQ5yqzGESqHW6Cz1i3fWBSIWtMZ6/AKhNaXjyNWk6wMOnNEa5KeNYuq59+FtSc2J8cUWBKVH0APLH6e6IU/MQ9Yi0x6OgsxSiFPqtheXdhbXSx86h6XSblojM0XOcnJVFsUH62IlElq1cPPToALnArMzNiD9OFKpeez6ikcKfMACKSK9zkerQ89oUsBsO0XjtYiT9MCJBQWERn2NM/hAxY2DnoW+BHfZ6PYJDi7g8a/WdBg3TRIe4OQ3TTqEqEOFeFIzRWTM5gnnIuv2wqREw6SNEXy/qFIIqjpJay3Fj1dXCiicBfE/yfmvWnNULcDPaiqlBZK0aPLPPRr2HqjciXNFsMdt5D6K9vZUfS7qFL3NqamVmNSz2FuiXqfKblcnC/qHI1J5qLl6VYwAWuH12EFklwzmvri9yUzXZ1V7W4r73xOA/O7rPoEH5rbFsVtG7rEB2zRc/frMlwXwocRk21cROfd7BajcWOMMDU0snVgekSpXV/BPqu6fii3OzVCrws0vOE4vO1YzGfO30MkzAqyQ3ZN/Vw6nDxQNgOJAux+btlsnpnNY+NPqsyVkXQgwC6oXCXnM8wWX1ODT43LxV4P+vflu29D5Onr6mnu/DP0iHyMJJKsfoQyp+WaB80z+NbmKrBI0+TXC2kLGjX2X4fHrsym7Pl+mUEsnH0rx3BCPIOH4b1+vZBviyjQm7SYqeyYGWXjyP4gFxtlnWDquFjZZyq+SKiPrmNHFjJsOfx5BlpJBLCh4bwSAysfzO0qADVVAsRJXPm4Fhpuc/GnX8ZqoMizFbrFic8asZIqyNOFpYxFps3mS+SGyiTqRbvVM/KJQXAQb5xEB9u6ha31iuPoM+E9aii4wc16RiJ9U/9FCvehmrsjEoM3Nn+4e1GcX7ijnWeVObyr2m3CJ36aH1ssWA08LvzfGPNyUbDBdbIYOFD/voPgmet+dPz3Po3cCT8vXHuMNy/UAYdRzaIJ2xXNvNr2EuJeyo3uQgoGSSbHGLz/O9RsxhiiI23tjva/ThMObfOP1fl54ltmj37zr1ymKFXccdFPwqF+JVsoMsUm0uNdbLlMheQogKJY1FlDgL3EJ+EfRI3yqxOXPfKxhz1cwpKFW1joel50MgjZQj72aEbtUFFmBtu1qtjpyXNwtYJhS4MTkTxcPksR5HEchD0wcopz1XBPiXWW80w7VtJOqrIfBG/OMvviwVSKKgitw05b/eJXmo0yKT6JIYZxlRofPxbf4vsbvSqJfRnKM0+JRPV3DjcpWX9fjVhnzZk/UGfRJ0+LZRVjp8MHLpLm7sPJGcABV42xc9pVxEXEqKm7sblbiT
  template:
    metadata:
      creationTimestamp: null
      name: harbor-oidc-secret
      namespace: harbor
    type: Opaque
