external-dns:
  global:
    security:
      allowInsecureImages: true
  image:
    registry: registry.k8s.io
    repository: external-dns/external-dns
    tag: v0.21.0
  sources:
    # - crd
    - service
    - ingress
    - gateway-httproute
    - gateway-tlsroute
    - gateway-udproute
    - gateway-tcproute
    - gateway-grpcroute

  provider: pihole

  extraArgs:
    pihole-api-version: 6
    target-net-filter: 192.168.178.245/24

  validation:
    enabled: true

  pihole:
    server: "http://pihole-web.pihole"
    tlsSkipVerify: ""
    secretName: "pihole-admin-secret"

  domainFilters:
    - 'internal.sealeo.io'

  excludeDomains: []

  regexDomainFilter: ""
  regexDomainExclusion: ""

  dryRun: false
  policy: sync

  crd:
    create: false

  service:
    revisionHistoryLimit: 0
    enabled: true

  serviceAccount:
    create: true

  rbac:
    create: true

  pdb:
    create: true

  metrics:
    enabled: false
