external-dns:
  sources:
    # - crd
    - service
    - ingress

  provider: pihole

  extraArgs:
    pihole-api-version: 6
    target-net-filter: 192.168.178.245/24

  validation:
    enabled: true

  pihole:
    server: "http://pihole-web.pihole"
    tlsSkipVerify: ""
    secretName: "pihole-admin-secret"

  domainFilters:
    - 'internal.sealeo.io'

  excludeDomains: []

  regexDomainFilter: ""
  regexDomainExclusion: ""

  dryRun: false
  policy: sync

  crd:
    create: false

  service:
    enabled: true

  serviceAccount:
    create: true

  rbac:
    create: true

  pdb:
    create: true

  metrics:
    enabled: false
