machine:
  type: worker
  nodeLabels:
    topology.kubernetes.io/zone: ""
    topology.kubernetes.io/region: ""
  install:
    disk: /dev/sdb
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: minipc-worker-2
auto: off
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp1s0
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp1s0