---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: AgCCiy328vFQDguQt98DiRm1+46bkXsInYRAyH2eIT6cwnLTjgG6smI/ekiputGYjoqiohkKpA/J6uNBX9uy65zpyUko8rvefpqFwqfTvtdhbCWzx7sySKZExUvyPnzajUY8I4+7gQwlwoJpMiyLo93MspH7IztIvw92JgV1qa/g/5pxdLeKhJ/jjc0DBKAWdjgLYVvdBO5MvmYabIXLA7aawqu1J6Ltq0N4zgGTjGmw4qUXHtJ8RKmGHnE6EGRRYRJMOV405kLwL8WgW6ZgpE3UEAGZ1s0nGH22ByloeWYnAAd7vwJoySFOJVbmkkynZB14uEpT8ToroXqGrl4K/RVK15upHMl4r0mwmG7rVRxeyu8amZI4gEDAsFMUMYQiV/sP2dtoUlgRKxRrjij3jiT0FmBw4YyQ0nNq/hWezTquV2Q5OiYqm0bDprG/2DhdocGxu/9YVFIxws/C/ZX81COzDu3J+a2QYA3QamaYRfb3bWup0vTAiVKnO5tbZkhsZ1O8SIk2E8flh7FULPoK98142Dax6FJ6agcI2ZAbxSx2Zxc/2zLQe1yoMr1QHChVEUxTqpJCIEJ9TZJPsbnPglxRUG6cxMz1BeG1qwn208dFw+gGjZ7YOaZgfqgMXMCfFcGVDTq1qh0ucrjNPpC6UKcXieKX2nmU9xbQhQeOLUNnZ0WzJ2WT/Rx9chXvIAa20MGlkQjJVW6rQsZH4AjozyixzKB/zeQsf7Kh+lbiA1rsdUJjTDVh6ECE
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
