apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: AgCTFx6OwbE0f4mu6w2vN27hs5o+xcqw1jy5KnBgmk8qTWV6cQ/K5mbDMzN5C3C97YneIG9qWXqX1B3EJb/h5IRPudvO7TBgi1opJl0Co5/tQeCQgigqq++qROCXIzSGe5WrMd0WYE2MDH+roOCdyp59V/6jed574icXbUl1a0qtsehsUX5WGVEWxat5syHI+iYKa1BoB6HTrM7weChNiH58BOtDSDBg53xUbJS6hc8KsXt9vRTOIPH3asmn/+B2wrJFz1McsHsq7U+BdtO3jYngFbWDMaSda7lm0Koudpq0SsZqkA5jm4KHcsSKyGEbV4ypMZuaJZ7dQMVMI544m4k/TsffY7PxFjnQ1MduAvoPl5Bo4faHofYzGRyhvyXTZ6eMAnxVpECFeNffwT76W1KTbh4rTd+NuEIouwAZTpUrLKSoqFjg3vBc0cxAR+8uVMCtemLE77kDf5QYoOkpE5ebEJ/CdRvGzykSXcFSKVjPEyJUuWwhfAkEGC1+wIWDsj8XDuj61MJtIp5oFlFKLKMhuf1/9TPU2wy7zQh9LBWMZKCNjLNIsBByo0ZVQce7J1BrEcZTB8dctOqZzUKWxR5xSZsAZ8qDDdoyYoy5pH+js+OFDGfMQD6xjzn6Hv6t4OVnInkbyCS0vqjRyLUmLJDm+1fkWlgcfWhCjM4FoeZMwUphZBunm0Et7om6lrOAOTMGPDxaQ9AsKPvXyQBgigR29RRfyLw2BOh2oAawkrOIfvLwROaPRKyk
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque