apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: AgAkuE8ou6WVUTMfDiESgBOmIpqMI0mbQn1lEcheChU+1bIpgwjPhg937CwsLKnB98I5cya+g7Y2Ba9G+Dazr2maYfpsDXo3oq91PeBLqRWnGTACia4zkLxw1v5yXQ91Xk0KC41g8x/zA4YdaHSxTVfXgoz6YtQKL5aE52UGMgL9PD02PlbSIW/MX2hWxtkToVn2bN4Scc/aHUu/JPRXHdiFfxBSlmMAmLb/fXi/NGxvtrx9QWe+adFGae2IxieiFND2miW+/r35KTtGEcXfgvIphWgaTdJ1HuPja9QqN9nNTMGj1sEh3LIRJ4CMXtBam8I0Q+J+gUauJ3hXgaMb6g3IdeCNczZ2GcbGdqRH6BT6TWtsogMYCWPAm26sFIucKEvJcPf6NyfPfKGo7AaIet+Ri8D52FiBW91Xzb3z9yCqMbOYCc2JkgHYAaJNXyJjd/QOV+YAvGj4Nn2p2cQ8zUgWjTjP/WLuNiuHPETIcQZfDyCRSoXfDufX+FSIJ8D3i0GlQlRQXQSauShv5n54Oj24TUZv1vcQdA1YcLVICFV3Lvvuz/vO3KGb269hH0spnDg+Pu3sxVhGhiQooVv8N49C7BeaOlLANm4vt5dC6Bv3Lsh4iL7ZwEAhPVw5i0Q6uZ9mYh26mux4vXhJTIfZm9kaY9bLNRxE9dE6+0O9GT36Ps8D7PaIFUy60Y2zvrF5koCTsYr0SjKTTwKTuC+eVLgTEPyKZokjMvvzXy05RC2sA0YFstBhxaWW
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager