metallb:
  rbac:
    create: false

  controller:
    enabled: true
    logLevel: info
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

  speaker:
    enabled: true
    logLevel: info
    resources:
      limits:
        cpu: 100m
        memory: 100Mi

  crds:
    enabled: true