apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.buildkit.replicas }}
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:latest
          securityContext:
            privileged: true  # Run as root with full privileges
          args: ["--addr", "unix:///run/buildkit/buildkitd.sock"]
          volumeMounts:
            - name: buildkit-socket
              mountPath: /run/buildkit
      volumes:
        - name: buildkit-socket
          emptyDir: {}