apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.buildkit.replicas }}
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: {{ .Values.buildkit.image }}
          args:
            - --addr
            - unix:///run/user/1000/buildkit/buildkitd.sock
            - --addr
            - tcp://0.0.0.0:1234
            # - --tlscacert
            # - /certs/ca.pem
            # - --tlscert
            # - /certs/cert.pem
            # - --tlskey
            # - /certs/key.pem
            - --oci-worker-no-process-sandbox
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          livenessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            initialDelaySeconds: 5
            periodSeconds: 30
          securityContext:
            seccompProfile:
              type: Unconfined
            appArmorProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 1234
          volumeMounts:
            # - name: certs
            #   readOnly: true
            #   mountPath: /certs
            - mountPath: /home/user/.local/share/buildkit
              name: buildkitd
      volumes:
        # - name: certs
        #   secret:
        #     secretName: buildkit-daemon-certs
        - name: buildkitd
          emptyDir: {}