apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.buildkit.replicas }}
  revisionHistoryLimit: {{ .Values.buildkit.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
        - name: buildkitd
          image: moby/buildkit:latest
          securityContext:
            privileged: true
          args: ["--addr", "tcp://0.0.0.0:1234"]
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: buildkit-socket
              mountPath: /run/buildkit
      volumes:
        - name: buildkit-socket
          emptyDir: {}