apiVersion: v1
kind: Service
metadata:
  labels:
    app: buildkitd
  name: buildkitd
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 1234
      protocol: TCP
  selector:
    app: buildkitd