longhorn:
  preUpgradeChecker:
    jobEnabled: false

  persistence:
    defaultClass: true
    defaultClassReplicaCount: 1 
    defaultDataLocality: best-effort
    defaultReplicaAutoBalance: best-effort
    defaultDiskSelector:
      enable: true
      selector: "nvme"

  csi:
    attacherReplicaCount: 1
    provisionerReplicaCount: 1
    resizerReplicaCount: 1
    snapshotterReplicaCount: 1

  defaultSettings:
    defaultReplicaCount: '1'
    defaultLonghornStaticStorageClass: longhorn
    defaultDataLocality: best-effort
    storageOverProvisioningPercentage: '100'
    storageMinimalAvailablePercentage: '20' 
    upgradeChecker: false
    failedBackupTTL: '60'
    logLevel: Warn
    backupCompressionMethod: lz4
    v2DataEngine: false
    backupConcurrentLimit: '5'
    restoreConcurrentLimit: '5'

  longhornUI:
    replicas: 1

  httproute:
    # -- Setting that allows Longhorn to generate HTTPRoute records for the Longhorn UI service using Gateway API.
    enabled: true
    # -- Gateway references for HTTPRoute. Specify which Gateway(s) should handle this route.
    parentRefs:
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https
    hostnames:
      - 'longhorn.internal.sealeo.io'

  ingress:
    enabled: false
    host: longhorn.internal.sealeo.io
    tls: true
    tlsSecret: longhorn-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dns